### ISSUE TITLE
how to find out that a peer has sent all the routes

### ISSUE THREAD

**Issue by jopietsch** [osrg/rustybgp#116]
in bgperf, it uses the count of how many prefixes received from a peer to know that a test has finished. When adding filter testing, just knowing the number of prefixes accepted isn't enough. It needs to know either the number of prefixes received before filters or the number of prefixes filtered, or that End-of-RIB has been sent. Is there anyway to get any of those things? with BIRD you can see the number of prefixes received and the number accepted. With FRRouting and OpenBGPD you can see when EOR has been sent.

**Comment by fujita** [comment]
The latest master sends eor messages.
Also you need the number of prefixes and accepted via the API, right?

**Comment by fujita** [comment]
Now the number of accepted routes are properly reported.
