### ISSUE TITLE
MRT injecting fails with "failed to send: EOF"

### ISSUE THREAD

**Issue by Cinderella-Man** [osrg/rustybgp#213]
Hello,

First of all - thank you for this great tool :pray: 

I'm trying to load an MRT dump file(https://data.ris.ripe.net/rrc03/2023.01/bview.20230101.0000.gz) using the `gobgp` CLI.

It works for ten records, but when I go to 100 or more, it returns:
```
root@abc:~# gobgp mrt inject global bview.20230101.0000 10
root@abc:~# gobgp mrt inject global bview.20230101.0000 100
failed to send: EOF
```

Do you have any idea why this could happen?

I appreciate any help you can provide.

Kamil

**Comment by fujita** [comment]
Thanks for the report! Can you try the latest master? Should be fixed by https://github.com/osrg/rustybgp/commit/310543d1bdd214cc6899b33e2897e883556bb42f

Looks like the mrt file includes routes that rustybgp can't handle. Fixed rustybgp to just ignore such rather than returning an error.

**Comment by Cinderella-Man** [comment]
Thank you very much for fixing the code so quickly. It's still parsing the file, but I assume that it now works fine.

For those routes that are ignored - would it be beneficial to log them somehow(even on the "debug" level)?

**Comment by Cinderella-Man** [comment]
Two additional things that I realised as it started to work:

1) I'm getting the following message printed multiple times as it parses:
```
failed to parse: unknown mup subtype: 185
```
As far as I know, the file should be fully compatible with the BGP specs, so this should be a valid route - have you ever seen this warning? We were getting the same from the `gobgp` router.

2) We are using a configuration that creates MRT update dumps every 60 seconds:
```
[[mrt-dump]]
  [mrt-dump.config]
    dump-type = "updates"
    file-name = "/tmp/mrt-updates-20160510.1546.dump"
    rotation-interval = 60
 ```
 
 What was happening with `gobgp` is that it was parsing the file name, and when it found the `20160510.1546` part, it was actually clever enough to understand that this it `Ymd.Hm` and it was storing data to *a new file* every 60 seconds, i.e. "/tmp/mrt-updates-20230131.1518.dump", "/tmp/mrt-updates-20230131.1519.dump" etc. - is there any chance that this could be supported?
 
 Please let me know if I should open separate issues for all three "problems" described above,
 
 Thanks,
 
 Kamil

**Comment by fujita** [comment]
`gobgp` command gives the following warning:

```
failed to parse: unknown mup subtype: 185
```

[MUP SAFI](https://github.com/osrg/gobgp/blob/master/pkg/packet/bgp/mup.go) looks like related. Please create an issue on gobgp.

About a way to dump MRT, feel free to create an issue on gobgp. Seems that everyone wants the own way to dump MRT. GoBGP can't support hundreds of ways to dump MRT. So I don't have any plan to add a new way though.

**Comment by Cinderella-Man** [comment]
Hello @fujita 

Thanks for your last answer. I just wanted to get back to dumping the MRT topic. What I tried to say is that I like the way that the `gobgp` is currently rotating dump files - I only pointed out that rustybgp is *not* behaving in the same way. Would it be possible to get consistent(or similar) behaviour as gobgp offers?

Thanks :pray: 

Kamil
