### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by furriest** [osrg/rustybgp#231]
When I tried to build RustyBGP on fresh Linux installation with Docker, I got this:

\# docker run --rm -it -v \"$(pwd)\":/home/rust/src ekidd/rust-musl-builder cargo build --release
...
   Compiling tonic-build v0.5.2
   Compiling hyper v0.14.25
error[E0599]: no method named \`send_replace\` found for struct \`Arc<tokio::sync::watch::Sender<Option<Connected>>>\` in the current scope
   --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.25/src/client/connect/mod.rs:225:17
    |
225 |         self.tx.send_replace(Some(connected.clone()));
    |                 ^^^^^^^^^^^^ method not found in \`Arc<tokio::sync::watch::Sender<Option<Connected>>>\`

For more information about this error, try \`rustc --explain E0599\`.
error: could not compile \`hyper\` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

Is there something wrong with my setup?
I have Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2

**Comment by marcelb98** [comment]
Getting the same error with `rust:1.68-bullseye` docker image basis.

**Comment by fujita** [comment]
Thanks for the report, fixed.
