### ISSUE TITLE
Route Server mode

### ISSUE THREAD

**Issue by dtaht** [osrg/rustybgp#242]
I am curious as to the roadmap for this effort. In particular, I am looking for a high speed route server, and trying to find alternatives....

**Comment by syadnom** [comment]
Unless libreqos is taking on an edge router / BNG type role, I'm not sure what this would be useful for at most *isps.  Even as a route server doing peering to an upstream provider, the operator's edge router still has to injest those routes and that's not any different than a direct peering unless you're going to do some filtering/aggregating.  I think it would require a bit of a rethink for a wisp.

Now, this would help reduce the number of 'heavy' peers to 1.  The route server could pull in any number of peers and chew those up with a fast CPU and then the operators edge router would just have the one peer to injest.

**Comment by dtaht** [comment]
My question was not specific to the libreqos use case, but as to the status of this project. Anything that can speed up BGP vs a vs BIRD or FRR would be welcomed in the general case.

**Comment by fujita** [comment]
If you are plan to compare the performances with production load, I'll put route server support on the top of TODO list.

**Comment by fujita** [comment]
Not tested much but supported.
